version: '3.5'

services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-front
    ports:
      - '3000:3000'
    env_file:
      - .env
#    networks:
#      - my-net

#networks:
#  my-net:
#    external: true