version: '3.5'

services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mediais-frontend
    ports:
      - '3000:3000'
#    volumes:
#      - .:/app
#      - /app/node_modules
    env_file:
      - .env
    networks:
      - my-net

networks:
  my-net:
    external: true